spring:
  application:
    name : ReactWithJavaBackend
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password:
    # driver-class-name: org.springframework.jdbc.datasource.DriverManagerDataSource
logging.level.org.springframework.security: off